server:
  port: 8083
 
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product_service_db
    username: root
    password: "Bidyut@07?"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://eureka-container:8761/eureka
    register-with-eureka: true
    fetch-registry: true
